### ISSUE TITLE
heap-buffer-overflow of grk_decompress in convert.cpp:403:22 in function planarToInterleaved

### ISSUE THREAD

**Issue by NigelX** [GrokImageCompression/grok#258]
Hi
I found an crash error.

System info：
Ubuntu 20.04 : clang 10.0.0 , gcc 9.3.0

grok release  v9.2.0 , commit 5806a91d3d04592cfb3ccc0aace621d52baf00c2

[crash.zip](https://github.com/GrokImageCompression/grok/files/6948501/crash.zip)

------------------------------------------
Verification steps：
1.Get the source code of grok
```
git clone https://github.com/GrokImageCompression/grok.git
```
2.Compile the grok
add CLFAGS="-fsanitize=address" CXXFLAGS="-fsanitize=address"
3.run
```
$ cd bin
$ ./grk_decompress -I crash.jp2 -o out.jpeg
```

```
=================================================================
==3090428==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x629000031600 at pc 0x0000005cb092 bp 0x7ffc31640c60 sp 0x7ffc31640c58
READ of size 16 at 0x629000031600 thread T0
    #0 0x5cb091 in void planarToInterleaved<1ul>(int const* const*, int*, unsigned long, int) /home/topsec/Downloads/grok/src/bin/common/convert.cpp:403:22
    #1 0x8cf6a6 in JPEGFormat::encodeStrip(unsigned int) /home/topsec/Downloads/grok/src/bin/image_format/JPEGFormat.cpp:604:3
    #2 0x549046 in grk::GrkDecompress::postProcess(_grk_plugin_decompress_callback_info*) /home/topsec/Downloads/grok/src/bin/jp2/grk_decompress.cpp:1545:12
    #3 0x4d65f6 in grk::GrkDecompress::decompress(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, grk::DecompressInitParams*) /home/topsec/Downloads/grok/src/bin/jp2/grk_decompress.cpp:872:5
    #4 0x55001f in grk::GrkDecompress::main(int, char**) /home/topsec/Downloads/grok/src/bin/jp2/grk_decompress.cpp:1613:8
    #5 0x552a05 in main /home/topsec/Downloads/grok/src/bin/jp2/grk_decompress.cpp:1659:16
    #6 0x7f228c2660b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16
    #7 0x42315d in _start (/home/topsec/Downloads/grok/bin/grk_decompress+0x42315d)

0x629000031600 is located 0 bytes to the right of 17408-byte region [0x62900002d200,0x629000031600)
allocated by thread T0 here:
    #0 0x49f872 in aligned_alloc /home/topsec/Downloads/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:192:3
    #1 0x7f228d144ddb in grk::GrkImage::allocData(_grk_image_comp*) /home/topsec/Downloads/grok/src/lib/jp2/util/GrkImage.cpp:184:24

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/topsec/Downloads/grok/src/bin/common/convert.cpp:403:22 in void planarToInterleaved<1ul>(int const* const*, int*, unsigned long, int)
Shadow bytes around the buggy address:
  0x0c527fffe270: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c527fffe280: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c527fffe290: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c527fffe2a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c527fffe2b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c527fffe2c0:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c527fffe2d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c527fffe2e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c527fffe2f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c527fffe300: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c527fffe310: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==3090428==ABORTING
```
Thank you,
Product Security

**Comment by boxerab** [comment]
Thanks a lot for the bug report - now fixed.
