### ISSUE TITLE
heap-buffer-overflow of grk_decompress of PNMFormat.cpp:847:11 in function encodeStrip

### ISSUE THREAD

**Issue by NigelX** [GrokImageCompression/grok#259]
Hi
I found an crash error.

System info：
Ubuntu 20.04 : clang 10.0.0 , gcc 9.3.0

grok release  v9.2.0 , commit 5806a91d3d04592cfb3ccc0aace621d52baf00c2

[crash2.zip](https://github.com/GrokImageCompression/grok/files/6948519/crash2.zip)

------------------------------------------
Verification steps：
1.Get the source code of grok
```
git clone https://github.com/GrokImageCompression/grok.git
```
2.Compile the grok
add CLFAGS="-fsanitize=address" CXXFLAGS="-fsanitize=address"
3.run
```
$ cd bin
$ ./grk_decompress -I crash.jp2 -o out.pnm
```
```
=================================================================
==3705636==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7fa2c14f4a80 at pc 0x0000005ffb01 bp 0x7fff6da02570 sp 0x7fff6da02568
READ of size 4 at 0x7fa2c14f4a80 thread T0
    #0 0x5ffb00 in PNMFormat::encodeStrip(unsigned int) /home/topsec/Downloads/grok/src/bin/image_format/PNMFormat.cpp:847:11
    #1 0x549046 in grk::GrkDecompress::postProcess(_grk_plugin_decompress_callback_info*) /home/topsec/Downloads/grok/src/bin/jp2/grk_decompress.cpp:1545:12
    #2 0x4d65f6 in grk::GrkDecompress::decompress(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, grk::DecompressInitParams*) /home/topsec/Downloads/grok/src/bin/jp2/grk_decompress.cpp:872:5
    #3 0x55001f in grk::GrkDecompress::main(int, char**) /home/topsec/Downloads/grok/src/bin/jp2/grk_decompress.cpp:1613:8
    #4 0x552a05 in main /home/topsec/Downloads/grok/src/bin/jp2/grk_decompress.cpp:1659:16
    #5 0x7fa2c8b2b0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16
    #6 0x42315d in _start (/home/topsec/Downloads/grok/bin/grk_decompress+0x42315d)

0x7fa2c14f4a80 is located 0 bytes to the right of 3547776-byte region [0x7fa2c1192800,0x7fa2c14f4a80)
allocated by thread T0 here:
    #0 0x49f872 in aligned_alloc /home/topsec/Downloads/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:192:3
    #1 0x7fa2c9a09ddb in grk::GrkImage::allocData(_grk_image_comp*) /home/topsec/Downloads/grok/src/lib/jp2/util/GrkImage.cpp:184:24

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/topsec/Downloads/grok/src/bin/image_format/PNMFormat.cpp:847:11 in PNMFormat::encodeStrip(unsigned int)
Shadow bytes around the buggy address:
  0x0ff4d8296900: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff4d8296910: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff4d8296920: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff4d8296930: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff4d8296940: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0ff4d8296950:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff4d8296960: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff4d8296970: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff4d8296980: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff4d8296990: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff4d82969a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==3705636==ABORTING
```

Thank you,
Product Security

**Comment by boxerab** [comment]
thanks for the report.
