### ISSUE TITLE
Memory leak on creating a BAD decompress object

### ISSUE THREAD

**Issue by frokaikan** [GrokImageCompression/grok#314]
Here is the code
```c++
#include "grok.h"

int main (int argc, char **argv) {
    auto stream = grk_stream_create_mapped_file_stream(argv[1], true);
    auto dec = grk_decompress_create((GRK_CODEC_FORMAT)976882234, stream);
    grk_object_unref(stream);
    grk_object_unref(dec);
}
```
The input can be arbitrary file.
Obviously, the `grk_decompress_create` takes a bad parameter, so I think it should return `nullptr` and do nothing.
However, when I run with `ASAN_OPTIONS=alloc_dealloc_mismatch=0`, I got the following report:
```
Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x4c41bd in operator new(unsigned long) 
    #1 0x7f623bd82281 in GrkCodec::GrkCodec() 
    #2 0x7f623bd835d1 in grk_decompress_create 
    #3 0x4c6afc in main 
    #4 0x7f623b2c1082 in __libc_start_main 
```
Is it a bug?

**Comment by boxerab** [comment]
Thanks for reporting - this was indeed a bug. Fixed now.
